#!/bin/sh

if [ "$(dirname $0)" = "." ]; then
  cd ..
fi

R=$(grep -rn \
        --exclude-dir=.git \
        --exclude-dir=node_modules \
        --exclude-dir=scripts \
        --exclude-dir=vendor \
        'gho_' .)

if [ "$?" = "0" ]; then
  echo Detect credential in project ...
  echo
  echo "$R"
  exit 1
fi
